services:
  - type: web
    name: kuis-bot-telegram
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false
